sudo: required
services:
  - docker

before_install:
  - docker build -t antoniovelichkov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antoniovelichkov/react-test npm test

after_success:
  - docker build -t antoniovelichkov/multi-client ./client
  - docker build -t antoniovelichkov/multi-nginx ./nginx
  - docker build -t antoniovelichkov/multi-server ./server
  - docker build -t antoniovelichkov/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push antoniovelichkov/multi-client
  - docker push antoniovelichkov/multi-nginx
  - docker push antoniovelichkov/multi-server
  - docker push antoniovelichkov/multi-worker
  
  deploy:
  provider: elasicbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-723553701279
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
